# -*- coding: utf-8 -*-
"""app123456.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p-OqWIQvhdppIXM-_kkjSJ_Q5ie3rqk5
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import warnings
import os

# Suppress warnings
warnings.filterwarnings('ignore')

# -------------------------------------------------------------------------------------------------
# 1. PAGE CONFIGURATION & CUSTOM CSS
# -------------------------------------------------------------------------------------------------
st.set_page_config(
    page_title="Air Quality Analysis & Prediction",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for Light Maroon Background, Sea Blue Nav, and Maroon Accents
st.markdown("""
    <style>
        /* Main Background - Light Maroon */
        .stApp {
            background-color: #F3E5E8;
        }

        /* Sidebar Background - Light Sea Blue */
        [data-testid="stSidebar"] {
            background-color: #E0FFFF;
            border-right: 2px solid #800000;
        }

        /* Text Colors & Headers - Maroon */
        h1, h2, h3, h4, h5, h6, .stMarkdown, p, label, .stMetricLabel {
            color: #800000 !important;
            font-family: 'Helvetica', sans-serif;
        }

        /* Buttons - Maroon Background, White Text */
        .stButton > button {
            background-color: #800000;
            color: white !important;
            border-radius: 10px;
            border: none;
            font-weight: bold;
        }
        .stButton > button:hover {
            background-color: #A52A2A;
            color: white !important;
        }

        /* Metric Cards */
        [data-testid="stMetricValue"] {
            color: #800000;
        }

        /* Navigation Radio Buttons */
        .stRadio > div {
            background-color: transparent;
        }
    </style>
""", unsafe_allow_html=True)

# -------------------------------------------------------------------------------------------------
# 2. DATA PROCESSING FUNCTIONS
# -------------------------------------------------------------------------------------------------
@st.cache_data
def load_data():
    """
    Tries to load 'final_aqi_cleaned_data.csv' automatically.
    Returns None if file is not found.
    """
    file_path = "final_aqi_cleaned_data.csv"

    if os.path.exists(file_path):
        try:
            df = pd.read_csv(file_path)
            return df
        except Exception as e:
            st.error(f"Error loading local file: {e}")
            return None
    return None

@st.cache_data
def process_data(df):
    """
    Cleans the dataframe (Date conversion, Feature Engineering, Filling Missing Values)
    """
    try:
        # Date Conversion
        if 'Date' in df.columns:
            df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
            if 'City' in df.columns:
                df.sort_values(by=['City', 'Date'], inplace=True)

            # Feature Engineering (Seasonality)
            df['Year'] = df['Date'].dt.year
            df['Month'] = df['Date'].dt.month_name()

            def get_season(month):
                if month in [12, 1, 2]: return 'Winter'
                elif month in [3, 4, 5]: return 'Summer'
                elif month in [6, 7, 8]: return 'Monsoon'
                else: return 'Post-Monsoon'

            df['Season'] = df['Date'].dt.month.apply(get_season)

        # Remove Duplicates
        df.drop_duplicates(inplace=True)

        # Identify Numeric Columns
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()

        # Handling Missing Values (Simple fill for robustness in app)
        df[numeric_cols] = df[numeric_cols].fillna(0)

        return df
    except Exception as e:
        st.error(f"Error processing data: {e}")
        return None

def train_model(df):
    """
    Trains an XGBoost Regressor.
    """
    # Define potential features
    possible_features = ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3', 'Benzene', 'Toluene', 'Xylene']
    target = 'AQI'

    # Validation
    if target not in df.columns:
        return None, None, None, "Target column 'AQI' not found."

    features = [col for col in possible_features if col in df.columns]
    if not features:
        return None, None, None, "No pollutant features found."

    X = df[features]
    y = df[target]

    # Fill NaNs specifically for modeling
    X = X.fillna(0)
    y = y.fillna(0)

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = XGBRegressor(n_estimators=100, learning_rate=0.05, max_depth=8, n_jobs=-1, random_state=42)
    model.fit(X_train, y_train)

    score = model.score(X_test, y_test)
    return model, features, score, None

# -------------------------------------------------------------------------------------------------
# 3. SIDEBAR NAVIGATION & DATA LOADING
# -------------------------------------------------------------------------------------------------
with st.sidebar:
    st.markdown("<h1 style='text-align: center;'>🌫️</h1>", unsafe_allow_html=True)
    st.markdown("<h3 style='text-align: center; color: #800000;'>Air Quality App</h3>", unsafe_allow_html=True)
    st.markdown("---")

    page = st.radio("Go to", ["Data Overview", "Exploratory Data Analysis", "Modelling & Prediction"])
    st.markdown("---")

    st.markdown("### Data Source")

    # AUTOMATIC LOADING LOGIC
    df_raw = load_data()
    df = None

    if df_raw is not None:
        st.success(" Dataset loaded automatically!")
        df = process_data(df_raw)
    else:
        st.warning(" 'all_cities_combined.csv' not found.")
        uploaded_file = st.file_uploader("Upload CSV manually", type=['csv'])
        if uploaded_file is not None:
            df_raw = pd.read_csv(uploaded_file)
            df = process_data(df_raw)

# -------------------------------------------------------------------------------------------------
# 4. PAGE: DATA OVERVIEW
# -------------------------------------------------------------------------------------------------
if page == "Data Overview":
    st.title(" Data Overview")

    if df is not None:
        # Metrics
        col1, col2, col3 = st.columns(3)
        col1.metric("Total Rows", df.shape[0])
        col2.metric("Total Columns", df.shape[1])
        if 'City' in df.columns:
            col3.metric("Cities Covered", df['City'].nunique())

        # Preview
        st.subheader("Data Preview")
        st.dataframe(df.head(), use_container_width=True)

        # Statistics
        st.subheader("Statistical Summary")
        st.dataframe(df.describe(), use_container_width=True)

        # Missing Data Visual
        st.subheader("Data Completeness")
        fig_missing = px.imshow(df.isnull(), title="Missing Values Heatmap (Cleaned)", color_continuous_scale='Viridis')
        st.plotly_chart(fig_missing, use_container_width=True)
    else:
        st.info("Waiting for data... Please ensure 'all_cities_combined.csv' is in the repository.")

# -------------------------------------------------------------------------------------------------
# 5. PAGE: EXPLORATORY DATA ANALYSIS (EDA)
# -------------------------------------------------------------------------------------------------
elif page == "Exploratory Data Analysis":
    st.title(" Exploratory Data Analysis")

    if df is not None:
        if 'City' in df.columns:
            selected_city = st.selectbox("Select City", df['City'].unique())
            city_df = df[df['City'] == selected_city]
        else:
            selected_city = "All Data"
            city_df = df

        # Time Series
        st.subheader(f" Pollution Trends: {selected_city}")
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        pollutant = st.selectbox("Select Parameter", numeric_cols, index=0 if 'AQI' not in numeric_cols else numeric_cols.index('AQI'))

        if 'Date' in city_df.columns:
            fig_line = px.line(city_df, x='Date', y=pollutant, title=f'{pollutant} over Time',
                               template='plotly_white', color_discrete_sequence=['#800000'])
            fig_line.update_xaxes(rangeslider_visible=True)
            st.plotly_chart(fig_line, use_container_width=True)

        col_eda_1, col_eda_2 = st.columns(2)

        # Correlation
        with col_eda_1:
            st.subheader(" Correlations")
            corr_matrix = df.select_dtypes(include=[np.number]).corr()
            fig_corr = px.imshow(corr_matrix, text_auto=False, aspect="auto", color_continuous_scale='RdBu_r')
            st.plotly_chart(fig_corr, use_container_width=True)

        # Seasonal
        with col_eda_2:
            st.subheader(" Seasonal Analysis")
            if 'Season' in df.columns:
                seasonal_avg = df.groupby('Season')[numeric_cols].mean().reset_index()
                fig_season = px.bar(seasonal_avg, x='Season', y=pollutant, color='Season',
                                    color_discrete_sequence=px.colors.qualitative.Bold)
                st.plotly_chart(fig_season, use_container_width=True)
    else:
        st.info("Waiting for data...")

# -------------------------------------------------------------------------------------------------
# 6. PAGE: MODELLING AND PREDICTION
# -------------------------------------------------------------------------------------------------
elif page == "Modelling & Prediction":
    st.title(" AQI Prediction (XGBoost)")

    if df is not None:
        if st.button(" Train Model"):
            with st.spinner("Training..."):
                model, features, score, error = train_model(df)
                if error:
                    st.error(error)
                else:
                    st.session_state['model'] = model
                    st.session_state['features'] = features
                    st.success(f"Model Trained! R² Score: {score:.4f}")

        if 'model' in st.session_state:
            st.markdown("---")
            st.markdown("### 🎛️ Predict AQI")

            input_data = {}
            cols = st.columns(3)
            features = st.session_state['features']

            for i, feature in enumerate(features):
                with cols[i % 3]:
                    val = st.number_input(f"{feature}", value=float(df[feature].mean()))
                    input_data[feature] = val

            if st.button(" Calculate"):
                input_df = pd.DataFrame([input_data])
                prediction = st.session_state['model'].predict(input_df)[0]

                # AQI Bucket Logic
                bucket, color = "Severe", "darkred"
                if prediction <= 50: bucket, color = "Good", "green"
                elif prediction <= 100: bucket, color = "Satisfactory", "lightgreen"
                elif prediction <= 200: bucket, color = "Moderate", "yellow"
                elif prediction <= 300: bucket, color = "Poor", "orange"
                elif prediction <= 400: bucket, color = "Very Poor", "red"

                st.markdown(f"""
                    <div style="background-color: {color}; padding: 20px; border-radius: 10px; text-align: center; margin-top:20px;">
                        <h2 style="color: white; margin:0; text-shadow: 1px 1px 2px black;">Predicted AQI: {prediction:.1f}</h2>
                        <h3 style="color: white; margin:0; text-shadow: 1px 1px 2px black;">{bucket}</h3>
                    </div>
                """, unsafe_allow_html=True)
    else:
        st.info("Waiting for data...")

st.markdown("---")
st.markdown("<div style='text-align: center; color: #800000;'>CMP7005 Project | Streamlit Cloud Ready</div>", unsafe_allow_html=True)
