# -*- coding: utf-8 -*-
"""app199999.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfe2NBg3gcS4vGblkl7QSwjBJcbbx2Os
"""

!head -n 5 data/all_cities_combined.csv

!ls -F data/

!mkdir -p data
# Since external data sources are unreliable, creating a dummy CSV for now.
!echo "City,Date,PM2.5,PM10,NO2,CO,SO2,O3" > data/all_cities_combined.csv
!echo "Delhi,2023-01-01,150,200,80,5,30,45" >> data/all_cities_combined.csv
!echo "Mumbai,2023-01-01,70,120,50,2,15,35" >> data/all_cities_combined.csv
!echo "Chennai,2023-01-01,40,60,20,1,10,25" >> data/all_cities_combined.csv
!echo "Kolkata,2023-01-01,180,250,90,7,40,55" >> data/all_cities_combined.csv
!echo "Bangalore,2023-01-01,60,100,45,3,20,30" >> data/all_cities_combined.csv

!pip install streamlit

import streamlit as st

st.set_page_config(
    page_title="Air Quality Forecasting System",
    layout="wide"
)

st.title("🌍 Air Quality Forecasting & Analysis Platform")
st.markdown("""
This interactive system allows users to explore air quality data,
perform exploratory analysis, and predict **PM2.5 concentrations**
using an advanced machine learning model.
""")

st.sidebar.success("Use the navigation menu above to explore the app.")

import streamlit as st
import pandas as pd

st.header("📊 Data Overview")

@st.cache_data
def load_data():
    return pd.read_csv("data/all_cities_combined.csv")

df = load_data()

st.subheader("Dataset Shape")
st.write(df.shape)

st.subheader("Sample Records")
st.dataframe(df.head(20))

st.subheader("Missing Values (%)")
missing = (df.isnull().mean() * 100).sort_values(ascending=False)
st.dataframe(missing)

st.subheader("City-wise Record Count")
st.bar_chart(df['City'].value_counts())

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

st.header("📈 Exploratory Data Analysis")

df = pd.read_csv("data/all_cities_combined.csv")

pollutants = ['PM2.5','PM10','NO2','CO','SO2','O3']
selected = st.selectbox("Select Pollutant", pollutants)

st.subheader(f"Distribution of {selected}")
fig, ax = plt.subplots()
sns.histplot(df[selected].dropna(), kde=True, ax=ax)
st.pyplot(fig)

st.subheader("Correlation Heatmap")
corr = df[pollutants].corr()
fig2, ax2 = plt.subplots(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap="coolwarm", ax=ax2)
st.pyplot(fig2)

st.markdown("""
**Insight:** PM2.5 shows strong correlation with PM10 and NO2,
indicating shared emission sources.
""")

import streamlit as st
import numpy as np
import pickle

st.header("🤖 PM2.5 Prediction")

# NOTE: The model file 'models/xgboost_pm25.pkl' is also missing.
# I will add a placeholder for now and address it in the next step if the error persists.
# For a full solution, you would need to train and save the model, or download it.
# with open("models/xgboost_pm25.pkl", "rb") as f:
#     model = pickle.load(f)

# Placeholder for the model for now to allow the app to run without the model file
class MockModel:
    def predict(self, features):
        # Return a dummy prediction based on input for demonstration
        return np.array([np.mean(features) * 2])

model = MockModel() # Using a mock model for now

st.subheader("Enter Pollutant Levels")

PM10 = st.number_input("PM10", 0.0, 1000.0, 100.0)
NO2 = st.number_input("NO2", 0.0, 500.0, 40.0)
CO = st.number_input("CO", 0.0, 50.0, 1.0)
SO2 = st.number_input("SO2", 0.0, 200.0, 10.0)
O3 = st.number_input("O3", 0.0, 300.0, 30.0)

if st.button("Predict PM2.5"):
    features = np.array([[PM10, NO2, CO, SO2, O3]])
    prediction = model.predict(features)[0]

    st.success(f"Predicted PM2.5: {prediction:.2f} µg/m³")

    if prediction <= 60:
        st.info("Air Quality: Moderate")
    elif prediction <= 120:
        st.warning("Air Quality: Poor")
    else:
        st.error("Air Quality: Very Poor / Severe")

def clean_data(df):
    df = df.dropna()
    df = df.drop_duplicates()
    return df
