# -*- coding: utf-8 -*-
"""app11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12AOoo2F16aDvkWDf8rAB5SkBVY6nJHND
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import warnings
import os


# Suppress warnings
warnings.filterwarnings('ignore')

# -------------------------------------------------------------------------------------------------
# 1. PAGE CONFIGURATION & CUSTOM CSS
# -------------------------------------------------------------------------------------------------
st.set_page_config(
    page_title="Air Quality Analysis & Prediction",
    page_icon="🌫️",
    layout="wide",
    initial_sidebar_state="expanded"
)


# Custom CSS for Light Maroon Background, Sea Blue Nav, and Maroon Accents
st.markdown("""
    <style>
        /* Main Background - Light Maroon */
        .stApp {
            background-color: #F3E5E8;
        }

        /* Sidebar Background - Light Sea Blue */
        [data-testid="stSidebar"] {
            background-color: #E0FFFF;
            border-right: 2px solid #800000;
        }

        /* Text Colors & Headers - Maroon */
        h1, h2, h3, h4, h5, h6, .stMarkdown, p, label, .stMetricLabel {
            color: #800000 !important;
            font-family: 'Helvetica', sans-serif;
        }

        /* Buttons - Maroon Background, White Text */
        .stButton > button {
            background-color: #800000;
            color: white !important;
            border-radius: 10px;
            border: none;
            font-weight: bold;
        }
        .stButton > button:hover {
            background-color: #A52A2A;
            color: white !important;
        }

        /* Metric Cards */
        [data-testid="stMetricValue"] {
            color: #800000;
        }

        /* Navigation Radio Buttons */
        .stRadio > div {
            background-color: transparent;
        }
    </style>
""", unsafe_allow_html=True)

# -------------------------------------------------------------------------------------------------
# 2. DATA PROCESSING FUNCTIONS
# -------------------------------------------------------------------------------------------------
@st.cache_data
def load_data(url):
    try:
        df = pd.read_csv('https://raw.githubusercontent.com/Seb85vickz/CMP7005-Programming-for-Data-Analysis/refs/heads/main/final_aqi_cleaned_data.csv')
        df

        # Ensuring Data parsing
        if 'Date' in df.columns:
            df['Date'] = pd.to_datetime(df['Date'])
            df['Year'] = df['Date'].dt.year
            df['Month'] = df['Date'].dt.month

        return df
    except Exception as e:
        st.error(f"Error loading data: {e}")
