# -*- coding: utf-8 -*-
"""app29999.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q77YhfkJd64ykbcieTQd3X_u9bUmdBF0
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import pickle
import os

# --- Page Configuration ---
st.set_page_config(page_title="Air Quality App", layout="wide")

# --- Title ---
st.title("🌍 Air Quality Analysis & Prediction")

# --- Sidebar Navigation ---
page = st.sidebar.radio("Navigate", ["🏠 Data Overview", "📊 EDA", "🤖 Prediction"])

# --- DATA LOADING MECHANISM (The Fix) ---
st.sidebar.header("📂 Data Source")
uploaded_file = st.sidebar.file_uploader("Upload your 'all_cities_combined.csv' here", type=["csv"])

@st.cache_data
def load_data(file):
    df = pd.read_csv(file)
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
    return df

if uploaded_file is not None:
    df = load_data(uploaded_file)
    st.sidebar.success("Data Loaded Successfully!")
else:
    # Fallback: Try to load from local path if user hasn't uploaded yet
    try:
        df = load_data("data/all_cities_combined.csv")
        st.sidebar.info("Loaded from local 'data' folder.")
    except:
        st.warning("⚠️ Please upload your dataset (CSV) in the sidebar to proceed.")
        st.stop() # Stop execution here until data is provided

# =========================================================
# PAGE 1: DATA OVERVIEW (Showing the Data)
# =========================================================
if page == "🏠 Data Overview":
    st.header("📋 Data Overview")

    # 1. Show the Dataframe
    st.subheader("Raw Data View")
    st.write("Here is the first 100 rows of your dataset:")
    st.dataframe(df.head(100), use_container_width=True)

    # 2. Show Statistics
    st.subheader("Dataset Statistics")
    col1, col2, col3 = st.columns(3)
    col1.metric("Total Rows", df.shape[0])
    col2.metric("Total Columns", df.shape[1])
    col3.metric("Cities Covered", df['City'].nunique())

    # 3. Show Missing Values
    st.subheader("Missing Data Check")
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    if not missing.empty:
        st.bar_chart(missing)
    else:
        st.success("No missing values found!")

# =========================================================
# PAGE 2: EXPLORATORY DATA ANALYSIS (EDA)
# =========================================================
elif page == "📊 EDA":
    st.header("📊 Exploratory Data Analysis")

    # Pollutant Trend
    city = st.selectbox("Select City", df['City'].unique())
    city_df = df[df['City'] == city]

    st.subheader(f"Pollution Trend in {city}")
    pollutant = st.selectbox("Select Pollutant", ['PM2.5', 'PM10', 'NO2', 'CO', 'SO2', 'O3'])

    fig = px.line(city_df, x='Date', y=pollutant, title=f"{pollutant} over Time")
    st.plotly_chart(fig, use_container_width=True)

    # Correlation
    st.subheader("Correlation Heatmap")
    numeric_df = df.select_dtypes(include=[np.number])
    corr = numeric_df.corr()
    fig_corr = px.imshow(corr, text_auto=True, color_continuous_scale='Viridis')
    st.plotly_chart(fig_corr, use_container_width=True)

# =========================================================
# PAGE 3: PREDICTION (Robust Logic)
# =========================================================
elif page == "🤖 Prediction":
    st.header("🤖 PM2.5 Prediction")

    # Check for model file
    model_path = "models/xgboost_pm25.pkl"

    if os.path.exists(model_path):
        try:
            with open(model_path, "rb") as f:
                model = pickle.load(f)

            st.success("Model Loaded!")

            # Input Sliders
            col1, col2, col3 = st.columns(3)
            with col1: pm10 = st.number_input("PM10", value=100.0)
            with col2: no2 = st.number_input("NO2", value=40.0)
            with col3: co = st.number_input("CO", value=1.0)

            col4, col5 = st.columns(2)
            with col4: so2 = st.number_input("SO2", value=10.0)
            with col5: o3 = st.number_input("O3", value=30.0)

            if st.button("Predict"):
                input_data = np.array([[pm10, no2, co, so2, o3]])
                pred = model.predict(input_data)[0]
                st.metric("Predicted PM2.5", f"{pred:.2f}")

        except Exception as e:
            st.error(f"Error loading model: {e}")
    else:
        st.warning(f"Model file not found at {model_path}. Please train your model and save it first.")